Added Guess Handling
Kanaz312/Lexic pull request #39
Opened 2022-02-28 00:44 UTC by dbolusan

Implementing Guess Handling for guesses made by user in comparison to challenge words.

2022-02-28 05:30 UTC, WJKw0k approved these changes

2022-02-28 05:30 UTC, WJKw0k commented on lexic-frontend/src/checkGuess.js
> +// 2 : Letter is in the word, correct index
Might want to add a enum or something instead of magic numbers - but not a big deal

2022-03-04 06:08 UTC, Kanaz312 requested changes
Return comments need some changes, but otherwise looks really nice!
Also nice job putting return comments

2022-03-04 06:08 UTC, Kanaz312 commented on lexic-frontend/src/checkGuess.js
> +// returns a list of status, reals, on status of correct letters
return comment is confusing. Not sure if the return is a list of status and reals or what. Also not sure what "on status of correct letters" means.

2022-03-04 06:16 UTC, dbolusan commented on lexic-frontend/src/checkGuess.js
> +// returns a list of status, reals, on status of correct letters
Sounds good! I rephrase the return comments to indicate that these are a list of integers that represents letters

2022-03-04 06:18 UTC, Kanaz312 approved these changes
Looks good!

2022-03-04 06:22 UTC, WJKw0k approved these changes
Looks good to me. Thanks for documenting the code!

2022-03-04 16:15 UTC, Tylertyca approved these changes
Looks good. Nice tests.

2022-03-04 19:05 UTC, merged